name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script with secret
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }},
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET  }},
          GENIUS_CLIENT_ID: ${{ secrets.GENIUS_CLIENT_ID  }},
          GENIUS_CLIENT_SECRET: ${{ secrets.GENIUS_CLIENT_SECRET  }},
          GENIUS_ACCESS_TOKEN: ${{  secrets.GENIUS_ACCESS_TOKEN  }},
          NGROK_AUTHTOKEN: ${{  secrets.NGROK_AUTHTOKEN  }},
          NGROK_AUTHTOKEN2: ${{  secrets.NGROK_AUTHTOKEN2  }}
        run: |
          echo "Running script with secret"
          
          
